# Generated by Django 2.0.6 on 2018-07-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(choices=[('unknown', '保密'), ('male', '男'), ('female', '女')], default='unknown', max_length=8, verbose_name='性别'),
        ),
    ]
