# Generated by Django 2.0.6 on 2018-07-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20180704_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_discuss',
            field=models.BooleanField(default=True, verbose_name='可否评论'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
    ]
