# Generated by Django 2.0.6 on 2018-07-06 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180705_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article2Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '文章分类映射表',
                'verbose_name_plural': '文章分类映射表',
                'db_table': 'luf_article_category',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article2category',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='文章'),
        ),
        migrations.AddField(
            model_name='article2category',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(through='article.Article2Category', to='article.Category', verbose_name='文章分类'),
        ),
        migrations.AlterUniqueTogether(
            name='article2category',
            unique_together={('article', 'category')},
        ),
    ]
