# Generated by Django 2.0.6 on 2018-07-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20180706_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(related_name='tags', through='article.Article2Tag', to='article.Tag', verbose_name='文章标签'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='categories', through='article.Article2Category', to='article.Category', verbose_name='文章分类'),
        ),
    ]
